spring:
  cache:
    type: redis
    redis:
      time-to-live: 600000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
app:
  auth:
    jwks-url: ${JWKS_URL:https://dev-oqil4wmd6j6lc77a.us.auth0.com/.well-known/jwks.json}